[env]
# BUBBLE="ON"
# INSERTION="ON"
# HEAP="ON"
# HOARE="ON"
# LUMOTO="ON"
# MERGE="ON"
COUNTING="ON"
STABLE="ON"
# SELECTION="ON"
DEFAULT_TEST_N="50000"
DEFAULT_DEBUG_N="5"

[alias]
r = "run -- "
rr = "run --release -- "